version: '3'
services:
  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    # depends_on:
    #   - mysql
  mysql:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db: